backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "posts"
    folder: "content/posts"
    create: true
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "date"}
    - {label: "Is Draft", name: "draft", widget: "boolean"}
    - {label: "Pin To Featured", name: "featured", widget: "boolean"}
    - {label: "Enable TOC", name: "toc", widget: "boolean"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Categories", name: "categories", widget: "string"}
    - {label: "Tags", name: "tags", widget: "string"}
    